---
# This is a role for setting up the server.

- name: Add user and set password
  user:
    name: '{{ username }}'
    password: '{{ password | password_hash(''sha512'') }}'
    shell: '/bin/bash'

- name: Install packages
  apt:
    pkg:
     - telnetd
     - nmap
     - apache2
     - vsftpd
    update_cache: yes

#- name: Change Telnet port
#  replace:
#    path: /etc/services
#    regexp: '23/tcp'
#    replace: '{{ telnet_port }}/tcp'

# xinetd must be installed after changing the Telnet port
#- name: Install xinetd package
#  apt:
#    name: xinetd

- name: Create privilege escalation vulnerability
  lineinfile:
    path: /etc/sudoers
    line: '{{ username }} ALL=(ALL) NOPASSWD:ALL'

#- name: Place flag
#  copy:
#    dest: '/home/{{ username }}/flag.txt'
#    owner: '{{ username }}'
#    content: "{{ flag }}\n"
#    mode: '0600'

#- name: Place second flag
#  copy:
#    dest: '/root/flag.txt'
#    owner: root
#    content: "{{ flag_2 }}\n"
#    mode: '0600'

#####
- name: Start Apache service
  service:
    name: apache2
    state: started

###################################################################
# Create some secret directories and files.
- name: Create super_secret directory
  file:
    path: /var/www/html/super_secret
    state: directory

- name: Create index.html file
  copy:
    dest: /var/www/html/index.html
    src: index.html

- name: Create super_secret index.html file
  copy:
    dest: /var/www/html/super_secret/index.html
    src: index2.html

- name: Configure secret Apache site
  copy:
    dest: /etc/apache2/sites-enabled/001-super_secret.conf
    src: 001-super_secret.conf
###################################################################
# - name: Specify username and password of user
#   expect:
#     command: htpasswd -c /etc/apache2/.htaccess_secret user
#     responses:
#       "New password:": "Password123"
#       "Re-type new password:": "Password123"

- name: Specify username and password of user2
  expect:
    command: htpasswd -c /etc/apache2/.htaccess_super_secret user2
    responses:
      "New password:": "{{ flag_1 }}"
      "Re-type new password:": "{{ flag_1 }}"

- name: Create a robots.txt file
  copy:
    dest: /var/www/html/robots.txt
    src: robots.txt
#################################################################

#### Open FTP port
# - name: Open ftp port
#   unit:
#     description: vsftpd FTP server
#     requires: network.target

#   service:
#     type: simple
#       exec_start: /usr/sbin/vsftpd
#       restart: always

#   install:
#     wantedBy: multi-user.target

# - name: Allow incoming connections on port 20/21
#   ufw:
#     rule: allow
#     port: 
#       - 20/tcp
#       - 21/tcp

# - name: Restart vsftpd service
#   become: true
#   service:
#     name: vsftpd
#     state: restarted


- name: Start vsftpd
  systemd:
    name: vsftpd
    state: started

###########################################################

- name: Create alias for client
  lineinfile:
    path: '/etc/hosts'
    line: '192.168.30.5 client'
...
